### ISSUE TITLE
Bug in shopping cart, mobile version only. 

### ISSUE THREAD

**Issue by pa-famme** [gregjotau/dawn-famme#37]
**Describe the current behavior**
Stretched product photos in shopping cart, on mobile version only. See screenshot.

**Describe the expected behavior**

Regular sized product photos.

**Version information (Dawn, browsers and operating systems)**
- Dawn Version: 1.0.0
- Chrome Version 91.0.4472.114
- macOS Version 11.3.1

**Possible solution**

**Additional context/screenshots**
Add any other context about the problem here. If applicable, add screenshots to help explain.
![IMG_3847](https://user-images.githubusercontent.com/92975223/152130619-f95af486-f024-4d5c-844e-ae8e8e0da4e6.PNG)

**Comment by pa-famme** [comment]
There is still something wrong with the shopping cart on mobile. See the new screenshot.

![IMG_3901](https://user-images.githubusercontent.com/92975223/152984245-2508c464-78a9-42e2-b9ad-7db0dc14b4f6.PNG)

**Comment by gregjotau** [comment]
Fixed by a dawn commit
