### ISSUE TITLE
Make margins on button section a setting / optional

### ISSUE THREAD

**Issue by sofiemoksness** [gregjotau/dawn-famme#44]
Is it possible to make margins on button section a setting or optional?
![buttons](https://user-images.githubusercontent.com/99190561/152798585-7506e544-3d08-4734-a169-8f7a48867b13.png)
Per now this is the least margin possible, however it is still a lot of space underneath the buttons. Should be an option to have less white space. 

Here's an example edited in canva to emphasize what I mean:
![spotrsbh](https://user-images.githubusercontent.com/99190561/152799000-9998b9cd-8a41-4745-973b-2ff2b2a3c402.png)

**Comment by gregjotau** [comment]
<img width="1300" alt="Screenshot 2022-03-03 at 14 02 29" src="https://user-images.githubusercontent.com/13047497/156569990-d6a850ae-201d-402c-9afa-96cc94234354.png">

**Comment by pa-famme** [comment]
This is not fixed yet.
