### ISSUE TITLE
Metafield for shipping date

### ISSUE THREAD

**Issue by rhfamme** [gregjotau/dawn-famme#51]
We want a metafield for shipping date where those arrows are. Is it possible to get a badget on the first picture as shown. The bolded date should be a metafield for the product. The other text should be retrieved from the nb.json

![github-metafiled-preorder-dato (2)](https://user-images.githubusercontent.com/99011309/156725421-48d122b6-e0db-4cb4-a982-f8d8c01e11a7.jpg)

**Comment by pa-famme** [comment]
This is done. This looks more clean, but It's also easier to apply/change pre-order date on different products.

<img width="1261" alt="Skjermbilde 2022-03-08 kl  12 45 29" src="https://user-images.githubusercontent.com/92975223/157232161-a87e0fc6-ad70-4351-82a2-101a69462ac6.png">

**Comment by pa-famme** [comment]
Forslag til endring


<img width="610" alt="Skjermbilde 2022-03-09 kl  13 11 03" src="https://user-images.githubusercontent.com/92975223/157441492-940f89e2-d1c3-4c90-ab66-0173d72b975c.png">

**Comment by gregjotau** [comment]
Probably easiest if only the "message" changes based on choosing variant. If in stock, then another message should show.

**Comment by gregjotau** [comment]
https://github.com/Shopify/dawn/pull/876

**Comment by gregjotau** [comment]
implemented, but not needed anymore.
