### ISSUE TITLE
Apply "estimated shipping date" meta field in shopping cart. 

### ISSUE THREAD

**Issue by pa-famme** [gregjotau/dawn-famme#52]
We want the estimated shipping date to be visible in our shopping cart for items that are available for pre-order. See the screenshot down below for reference.

<img width="707" alt="Skjermbilde 2022-04-07 kl  10 28 43" src="https://user-images.githubusercontent.com/92975223/162155732-dbd402f8-6656-48b2-a032-4b298095e81e.png">

**Comment by gregjotau** [comment]
no need for now
